include:
  - "_next"
  - "**.html"
  - "**.json"
  - "_next/**"

exclude:
  - "README.md"

safe: true
highlighter: rouge
lsi: false
future: false
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
