name: Deploy to GitHub Pages

on:
  push:
    branches: [ deploy-github-pages, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --no-fund --no-audit

      - name: Install zustand
        run: npm install zustand

      - name: Install react-input-mask
        run: npm install react-input-mask @types/react-input-mask

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Configure Jekyll
        run: |
          mkdir -p out/assets/css
          echo -e "---\n---\n/* Empty file for Jekyll */" > out/assets/css/style.scss
          echo -e "include:\n  - \"_next\"\n  - \"**.html\"\n  - \"**.json\"\n  - \"_next/**\"\n\nexclude:\n  - \"README.md\"\n\nsafe: true\nhighlighter: rouge\nlsi: false\nfuture: false\nincremental: false\ngist:\n  noscript: false\nkramdown:\n  math_engine: mathjax\n  syntax_highlighter: rouge" > out/_config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
